# Generated by Django 5.2.16 on 2026-07-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=True, verbose_name="Passwortänderung erforderlich"),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administration"),
                    ("school_management", "Schulleitung"),
                    ("class_teacher", "Klassenlehrperson"),
                    ("subject_teacher", "Fachlehrperson"),
                ],
                default="subject_teacher",
                max_length=32,
                verbose_name="Rolle",
            ),
        ),
    ]
