# Generated by Django 5.2.16 on 2026-07-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("student_number", models.CharField(max_length=50, verbose_name="Interne Schülernummer")),
                ("first_name", models.CharField(max_length=150, verbose_name="Vorname")),
                ("last_name", models.CharField(max_length=150, verbose_name="Nachname")),
                ("birth_date", models.DateField(verbose_name="Geburtsdatum")),
                ("entry_date", models.DateField(blank=True, null=True, verbose_name="Eintrittsdatum")),
                ("exit_date", models.DateField(blank=True, null=True, verbose_name="Austrittsdatum")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="schools.school",
                        verbose_name="Schule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schülerin oder Schüler",
                "verbose_name_plural": "Schülerinnen und Schüler",
                "ordering": ("last_name", "first_name"),
            },
        ),
        migrations.CreateModel(
            name="ClassEnrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_date", models.DateField(verbose_name="Eintritt in die Klasse")),
                ("exit_date", models.DateField(blank=True, null=True, verbose_name="Austritt aus der Klasse")),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="classes.schoolclass",
                        verbose_name="Klasse",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="students.student",
                        verbose_name="Schüler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Klassenzuordnung",
                "verbose_name_plural": "Klassenzuordnungen",
                "ordering": ("school_class", "student"),
            },
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(fields=("school", "student_number"), name="unique_student_number"),
        ),
        migrations.AddConstraint(
            model_name="classenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "school_class"), name="unique_student_class_enrollment"
            ),
        ),
    ]
