# Generated by Django 5.2.16 on 2026-07-11 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Bezeichnung")),
                ("grade_level", models.CharField(max_length=20, verbose_name="Klassenstufe")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="led_classes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Klassenlehrperson",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="schools.schoolyear",
                        verbose_name="Schuljahr",
                    ),
                ),
            ],
            options={
                "verbose_name": "Klasse",
                "verbose_name_plural": "Klassen",
                "ordering": ("school_year", "name"),
                "constraints": [models.UniqueConstraint(fields=("school_year", "name"), name="unique_class_name")],
            },
        ),
    ]
