# Generated by Django 5.2.16 on 2026-07-11 09:02

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Bezeichnung")),
                ("short_name", models.CharField(max_length=20, verbose_name="Kurzbezeichnung")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Reihenfolge")),
                ("is_mandatory", models.BooleanField(default=True, verbose_name="Pflichtfach")),
                ("show_on_report", models.BooleanField(default=True, verbose_name="Auf Zeugnis anzeigen")),
                (
                    "grade_min",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=4, verbose_name="Kleinste Note"
                    ),
                ),
                (
                    "grade_max",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("6.00"), max_digits=4, verbose_name="Größte Note"
                    ),
                ),
                (
                    "grade_step",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Schrittweite",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="schools.school",
                        verbose_name="Schule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fach",
                "verbose_name_plural": "Fächer",
                "ordering": ("sort_order", "name"),
                "constraints": [
                    models.UniqueConstraint(fields=("school", "short_name"), name="unique_subject_short_name")
                ],
            },
        ),
    ]
