# Generated by Django 5.2.16 on 2026-07-11 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
        ("schools", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "report_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="schools.reportperiod",
                        verbose_name="Zeugnisperiode",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="classes.schoolclass",
                        verbose_name="Klasse",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to="subjects.subject",
                        verbose_name="Fach",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Lehrperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unterrichtszuordnung",
                "verbose_name_plural": "Unterrichtszuordnungen",
                "ordering": ("school_class", "subject", "teacher"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("teacher", "school_class", "subject", "report_period"),
                        name="unique_teaching_assignment",
                    )
                ],
            },
        ),
    ]
