# Generated by Django 5.2.16 on 2026-07-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("subjects", "0002_teachingassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeSheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "In Bearbeitung"), ("completed", "Abgeschlossen")],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Abgeschlossen am")),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_sheet",
                        to="subjects.teachingassignment",
                        verbose_name="Unterrichtszuordnung",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_grade_sheets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Abgeschlossen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Noteneingabe",
                "verbose_name_plural": "Noteneingaben",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.DecimalField(decimal_places=2, max_digits=4, verbose_name="Note")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="Version")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Geändert am")),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changed_grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades",
                        to="students.student",
                        verbose_name="Schüler",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades",
                        to="grades.gradesheet",
                        verbose_name="Noteneingabe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Noten",
                "ordering": ("student__last_name", "student__first_name"),
                "constraints": [
                    models.UniqueConstraint(fields=("sheet", "student"), name="unique_grade_per_sheet_student")
                ],
            },
        ),
    ]
