# Generated by Django 5.2.16 on 2026-07-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=80, verbose_name="Aktion")),
                ("object_type", models.CharField(max_length=80, verbose_name="Objekttyp")),
                ("object_id", models.CharField(max_length=80, verbose_name="Objekt-ID")),
                ("old_values", models.JSONField(default=dict, verbose_name="Alte Werte")),
                ("new_values", models.JSONField(default=dict, verbose_name="Neue Werte")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Zeitpunkt")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit-Ereignis",
                "verbose_name_plural": "Audit-Ereignisse",
                "ordering": ("-created_at",),
            },
        ),
    ]
