# Generated by Django 5.2.16 on 2026-07-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("street", models.CharField(blank=True, max_length=200, verbose_name="Straße und Hausnummer")),
                ("postal_code", models.CharField(blank=True, max_length=20, verbose_name="Postleitzahl")),
                ("city", models.CharField(blank=True, max_length=120, verbose_name="Ort")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="E-Mail")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Telefon")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Schule",
                "verbose_name_plural": "Schulen",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, verbose_name="Bezeichnung")),
                ("start_date", models.DateField(verbose_name="Beginn")),
                ("end_date", models.DateField(verbose_name="Ende")),
                ("is_active", models.BooleanField(default=False, verbose_name="Aktiv")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_years",
                        to="schools.school",
                        verbose_name="Schule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schuljahr",
                "verbose_name_plural": "Schuljahre",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="ReportPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Bezeichnung")),
                ("start_date", models.DateField(verbose_name="Beginn")),
                ("end_date", models.DateField(verbose_name="Ende")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparation", "Vorbereitung"),
                            ("open", "Eingabe geöffnet"),
                            ("review", "Prüfung"),
                            ("released", "Freigegeben"),
                            ("completed", "Abgeschlossen"),
                            ("archived", "Archiviert"),
                        ],
                        default="preparation",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_periods",
                        to="schools.schoolyear",
                        verbose_name="Schuljahr",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeugnisperiode",
                "verbose_name_plural": "Zeugnisperioden",
                "ordering": ("school_year", "start_date"),
            },
        ),
        migrations.AddConstraint(
            model_name="schoolyear",
            constraint=models.UniqueConstraint(fields=("school", "name"), name="unique_school_year_name"),
        ),
        migrations.AddConstraint(
            model_name="reportperiod",
            constraint=models.UniqueConstraint(fields=("school_year", "name"), name="unique_report_period_name"),
        ),
    ]
