# Generated by Django 5.2.16 on 2026-07-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Bezeichnung")),
                ("report_type", models.CharField(max_length=100, verbose_name="Zeugnisart")),
                ("grade_level", models.CharField(blank=True, max_length=20, verbose_name="Klassenstufe")),
                (
                    "template_key",
                    models.SlugField(
                        help_text="Verweist später auf eine geprüfte, versionierte HTML-Vorlage.",
                        max_length=100,
                        verbose_name="Vorlagenschlüssel",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, verbose_name="Version")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_templates",
                        to="schools.school",
                        verbose_name="Schule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeugnisvorlage",
                "verbose_name_plural": "Zeugnisvorlagen",
                "ordering": ("name", "-version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "template_key", "version"), name="unique_report_template_version"
                    )
                ],
            },
        ),
    ]
